---
- hosts: all
  become: yes
  # gather_facts will fail under some circumstances related to the ansible_port != 22, and the ssh-port being 22 on
  # unconfigured systems. The rule 'change-sshd-port' will gather the facts as its last task
  gather_facts: false 

  roles:
    - role: ../roles/change-sshd-port
      become: no

  handlers:
    - name: restart qemu-guest-agent
      service: 
        name: qemu-guest-agent
        state: restarted

  tasks:
    - name: Update apt cache if needed
      apt: 
        update_cache: yes 
        cache_valid_time: 3600

    - name: Upgrade all packages (apt)
      apt:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Install QEMU Guest Agent
      package:
        name: qemu-guest-agent
        state: latest
      notify: restart qemu-guest-agent

    - import_tasks: ../tasks/locale.yml

    - import_tasks: ../tasks/hardening.yml
